version: "3.7"
services:
    ProjectA:
        image: project-a:latest
        restart: always
        depends_on:
            - MariaDB
        links: 
            - MariaDB
        ports:
            - 8080:8080
    ProjectB:
        image: project-b:latest
        restart: on-failure
        depends_on:
            - MariaDB
            - ProjectA
        links: 
            - MariaDB
        ports:
            - 8081:8081
    MariaDB:
        image: mariadb:10.4.11-bionic
        restart: on-failure
        environment: 
            MYSQL_ROOT_PASSWORD: "root"
        ports:
            - 3306:3306
