version: "3.7"
services:
    ProjectA:
        image: project-a:latest
        restart: always
        ports: 
            - 8080:8080
    ProjectB:
        image: project-b:latest
        restart: always
        depends_on: MariaDB
        ports: 
            - 8081:8081
    MariaDB:
        image: mariadb:10.4.11-bionic
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: "root"
        ports:
            - 3306:3306